<?php

/**
 * @file
 * Ip_image module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ip_image_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.ip_image':
            $text = file_get_contents(dirname(__FILE__) . "/README.md");
            if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
                return '<pre>' . $text . '</pre>';
            } else {
                // Use the Markdown filter to render the README.
                $filter_manager = \Drupal::service('plugin.manager.filter');
                $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
                $config = ['settings' => $settings];
                $filter = $filter_manager->createInstance('markdown', $config);
                return $filter->process($text, 'en');
            }
    }
    return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ip_image_theme($existing, $type, $theme, $path)
{
    return [
        'paragraph__ip_image' => [
            'base hook' => 'paragraph',
        ],
        'media__image' => [
            'base hook' => 'media',
        ],
    ];
}
