<?php

/**
 * @file
 * Ip_views_embed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ip_views_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ip_views_embed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ip_views_embed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ip_views_embed' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_ve_view' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_ve_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips from idfive" helper text to the paragraph.
 */
function ip_views_embed_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ip_views_embed') {

    // Additional help text from idfive.
    $markup = '<p>This Kitchen Sink widget embeds existing views blocks in a page. It is neccesary to first create and style the view desired. This level of work is usually best done by a developer. If you do not follow what a drupal view is, or how to style one, best not to use this.</p>';
    $markup .= '<p><a target="_blank" href="/admin/help/ip_table">Views Embed Module Help</a></p>';
    $element['ip_views_embed_help'] = [
      '#type' => 'details',
      '#title' => t('Additional Help'),
      '#weight' => -999,
    ];
    $element['ip_views_embed_help']['#markup'] = $markup;

  }
}
