<?php

/**
 * @file
 * Implements various hooks and functions to run the Admin Toolbar module.
 */

use Drupal\Core\Menu\LocalTaskManager;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Shows the module's readme file on the help page.
 */
function idfive_admin_toolbar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.idfive_admin_toolbar':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (\Drupal::moduleHandler()->moduleExists('markdown')) {
        // TODO Add markdown support.
        $output = '<pre>' . $readme . '</pre>';
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }
      return $output;
  }
}

/**
 * Implements hook_toolbar().
 *
 * Adds admin edit links/tabs in toolbar, so we dont need to have tabs on pages.
 */
function idfive_admin_toolbar_toolbar() {
  $links = [];
  $local_tasks = LocalTaskManager::getLocalTasks();
  if (empty($local_tasks['tabs'])) {
    return $links;
  }
  foreach ($local_tasks['tabs'] as $route_name => $value) {
    // Add to array by #weight so that we have the correct order.
    $links[$value['#weight']] = $value['#link'];
  }
  // Sort into correct order.
  ksort($links);
  // Add the menu local tasks into the toolbar.
  $items['local_tasks'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'html_tag',
      '#tag' => 'button',
      '#value' => t('Edit'),
      '#attributes' => [
        'title' => t('Local tasks'),
        'class' => ['toolbar-icon', 'toolbar-icon-edit'],
      ],
      '#cache' => [
        'contexts' => [
          'url.path',
        ],
      ],
    ],
    'tray' => [
      '#heading' => t('Local tasks'),
      'toolbar_administration' => [
        '#attributes' => [
          'class' => ['toolbar-menu'],
        ],
        '#links' => $links,
        '#theme' => 'links__toolbar_MY_MODULE',
      ],
    ],
    '#weight' => 1000,
  ];
  return $items;
}
