<?php

/**
 * @file
 * Ip_video module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ip_video_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.ip_video':
            $text = file_get_contents(dirname(__FILE__) . "/README.md");
            if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
                return '<pre>' . $text . '</pre>';
            } else {
                // Use the Markdown filter to render the README.
                $filter_manager = \Drupal::service('plugin.manager.filter');
                $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
                $config = ['settings' => $settings];
                $filter = $filter_manager->createInstance('markdown', $config);
                return $filter->process($text, 'en');
            }
    }
    return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ip_video_theme($existing, $type, $theme, $path)
{
    return [
        'paragraph__ip_video' => [
            'base hook' => 'paragraph',
        ],
        'media__remote_video' => [
            'base hook' => 'media',
        ],
    ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips from idfive" helper text to the paragraph.
 */
function ip_video_field_widget_paragraphs_form_alter(&$element, &$form_state, $context)
{
    if ($element['#paragraph_type'] == 'ip_video') {

        // Tips text from idfive.
        $markup = '<h3>Do:</h3><ul>';
        $markup .= '<li><strong>Limit the use of video</strong> Video can slow down site rendering.</li>';
        $markup .= '<li><strong>Use short videos that convey a message</strong></li>';
        $markup .= '</ul>';
        $markup .= '<h3>Dont:</h3><ul>';
        $markup .= '<li><strong>Overuse videos.</strong> These should be used sparingly.</li>';
        $markup .= '</ul>';
        $markup .= '<p><a target="_blank" href="/admin/help/ip_video">Video Module Help</a></p>';
        $element['ip_video_tips'] = [
            '#type' => 'details',
            '#title' => t('Video Embed Tips'),
            '#weight' => -1000,
        ];
        $element['ip_video_tips']['#markup'] = $markup;
    }
}
