<?php

/**
 * @file
 * Ip_table module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ip_table_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ip_table':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ip_table_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ip_table' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_tb_table' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_tb_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips from idfive" helper text to the paragraph.
 */
function ip_table_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ip_table') {

    // Tips text from idfive.
    $markup = '<h3>Do:</h3><ul>';
    $markup .= '<li><strong>Keep table headers short as possible.</strong> If you have 5 or more columns, long table headers will get harder to read at smaller screen sizes.</li>';
    $markup .= '</ul>';
    $markup .= '<h3>Dont:</h3><ul>';
    $markup .= '<li><strong>Use Tables for non tabular data.</strong> Other widgets will display these items much better.</li>';
    $markup .= '<li><strong>Use fewer than 3 rows.</strong></li>';
    $markup .= '</ul>';
    $markup .= '<p><a target="_blank" href="/admin/help/ip_table">Table Module Help</a></p>';
    $element['ip_table_tips'] = [
      '#type' => 'details',
      '#title' => t('Table Content Tips'),
      '#weight' => -1000,
    ];
    $element['ip_table_tips']['#markup'] = $markup;

  }
}
